### PR TITLE
Add Erlang/Escript

### PR DESCRIPTION
**Pull request by pichi**

### CODE REVIEW

**Comment by drujensen** [comment]
Question, can you change to add a conditional `if`?  The goal is to match the same code as this:
```ruby
def fib(n)
  return 1 if n <= 1
  fib(n - 1) + fib(n - 2)
end
```

**Comment by pichi** [comment]
@drujensen, Of course, I could but it would not be Erlang idiomatic code. The current code does the same number of recursions and operations as original one so it doesn't change benchmark purpose.

**Comment by sagesan** [comment]
Honestly, it should utilize ifs if they are available in the language. Every other language uses them, even when it's not idiomatic.

**Comment by OvermindDL1** [comment]
`if`'s in erlang/elixir are not even remotely like if's in other languages for note, idiomatic or not.  An `if` in erlang is a repeating cond pipeline.  Having the 0/1 in the head is the closest concept to an `if` as a match in erlang.  Something like C++ or Go or Ruby doesn't have a concept for something even like Erlang's `if`.

**Comment by drujensen** [comment]
Hhmm, I may have messed up the Elixir one then.  Should I change it back?  https://github.com/drujensen/fib/blob/master/Fib.exs

**Comment by drujensen** [comment]
@OvermindDL1 Question, if erlang using a `case` statement for `if's`, shouldn't we still use it?  To me, this is an issue with this specific language and in my mind should be reflected in the benchmark.

**Comment by OvermindDL1** [comment]
@drujensen The elixir link you linked that `if` is not even like Erlang's `if` (erlang's `if` in Elixir is called `cond`).  Elixir's `if` is a macro that will convert:
```elixir
  def fib(n) do 
    if n <= 1 do
      1
    else
      fib(n-1) + fib(n-2) 
    end
  end
```
To become:
```elixir
  def fib(n) do 
    cond do
      n <= 1 -> 1
      true -> fib(n-1) + fib(n-2)
    end
  end
```

The correct way to perform conditional branching (the most `if` like code at the compiled level to other languages) would be either of:
```elixir
  def fib(0), do: 1
  def fib(1), do: 1
  def fib(n), do: fib(n-1) + fib(n-2)
```
Or this (which is 'generally' slightly slower as it actually incurs more conditional checks, though the optimizer can sometimes fix that, sometimes...):
```elixir
  def fib(n) when n<=1, do: 1
  def fib(n), do: fib(n-1) + fib(n-2)
```
Or if you want to get a proper crash for invalid values (<0):
```elixir
  def fib(n) when n in [0, 1], do: 1
  def fib(n), do: fib(n-1) + fib(n-2)
```
And that least one will actually compile to become the multi-head case again anyway.

And yes, Elixir has code-rewriting hygenic macro's, most of the language is implemented as such on top of the few 'base' primitives (like `case` and function heads).

> @OvermindDL1 Question, if erlang using a case statement for if's, shouldn't we still use it? To me, this is an issue with this specific language and in my mind should be reflected in the benchmark.

Erlang is *very* based on a prolog style so it is quite non-traditional.

To be specific, in Erlang:
`if` chains (Elixir's name of it as `cond` definitely makes it less confusingly named) compile into case's, which is what top-level heads compile into as well, though top-level cases are slightly more efficient than any other calls, as well as are far *far* more readable.

Thus using an `if` like you are wanting to in erlang would end up being:
```erlang
fib(N) ->
  if
    N <= 1 -> 1
    true -> fib(N-1) + fib(N-2)
  end.
```
Which when compiled becomes:
```erlang
fib(N) ->
  case
    _ when N <= 1 -> 1
    _ when True -> fib(N-1) + fib(N-2)
  end.
```
Which is a tiny bit less efficient than but conceptually identical to:
```erlang
fib(N) when N <= 1 -> 1
fib(N) -> fib(N-1) + fib(N-2)
```

In erlang you do branching by function heads.  In general if you have a case/if/cond in a body then the function really should be broken up into more functions (functions should be tiny, better to make more functions, the system optimizes many functions better than fewer larger functions).

It is very prolog'y, not just in syntax but in a lot of conceptual ideas.

**Comment by drujensen** [comment]
@OvermindDL1 Thanks for the detailed explanation.  So, all the other ones are checking for `<=`. Would you agree that this is the closest resemblance to the code being tested?
```
def fib(n) when n<=1, do: 1
def fib(n), do: fib(n-1) + fib(n-2)
```

**Comment by OvermindDL1** [comment]
> Would you agree that this is the closest resemblance to the code being tested?

Correct, same for both elixir and erlang (they are the same language, just different syntax, adjust syntax too of course).  It's not strictly the most elixir'y "correct" interpretation (which would be to fail on invalid input and use head matchers instead of guards), but it is the closest to how all the other languages do it.

**Comment by drujensen** [comment]
@OvermindDL1 do you mind updating them?  This is obviously not in my wheelhouse yet.

**Comment by OvermindDL1** [comment]
@drujensen Sure, done, tested, committed, pushed.

**Pull request merged**
