### PR TITLE
Tail recursive Fibonacci implementation in OCaml

### PR DESCRIPTION
**Pull request by agrison**
Tail recursive Fibonacci implementation in Objective Caml.

On my Mac:

Naive implementation

    $ time ./fib
    2971215073
    
    real	0m9.933s
    user	0m9.486s
    sys	0m0.103s

With tail recursion

    $ time ./fib-tailrec
    2971215073
    
    real	0m0.004s
    user	0m0.002s
    sys	0m0.002s

### CODE REVIEW

**Comment by OvermindDL1** [comment]
This is a different algorithm though, it's linear instead of exponential, so perhaps the cheating section?

**Comment by agrison** [comment]
Yes it's not exactly the same algorithm. It's still being recursive though but the compiler makes some proper optimization to it eliminating un-needed stack frames (well keeping only one really).

You can put it in the section you want to :)

**Comment by OvermindDL1** [comment]
> You can put it in the section you want to :)

Personally I'd opt for a folder per algorithm of fib, implement those the whole way across, though testing the faster ones will be far more difficult to do accurately, might have to bake a statistical measurement library inside each of those or so if they were taken...

**Comment by rbjorklin** [comment]
@agrison I feel like I have a learning opportunity here. From the signature it looks like `fib` doesn't have any parameters but one argument is clearly given. Could you explain to me how your `fib` implementation works?

Also in [my PR](https://github.com/drujensen/fib/pull/43) for the naive implementation I was unable to get rid of the `else` block as requested and with my limited knowledge I don't think it's possible. Maybe you could have a look and possibly correct me? :smiley:

**Comment by agrison** [comment]
Just FYI it's not memoization at all.

**Comment by drujensen** [comment]
@agrison thanks!

**Pull request merged**
