### PR TITLE
Faster / more idiomatic Pascal version

### PR DESCRIPTION
**Pull request by Akira13641**
This uses `case of` instead of an if statement (which tends to generate better code in many scenarios) and also changes the input type from `Int64` to `UInt64` so as to be closer to most of the other programs.

### CODE REVIEW

**Comment by drujensen** [comment]
Thanks for the PR.

All of the other languages are using an `if` conditional.  It wouldn't be comparable to use a `case` statement here.

It should match this code snippet (ruby) as close as possible:
```
def fib(n)
  return 1 if n <= 1
  fib(n - 1) + fib(n - 2)
end
```

**Comment by OvermindDL1** [comment]
> It should match this code snippet (ruby) as close as possible:

`if`'s in pascal are not quite how they are in, say, ruby, different performance characteristics (and code flow handling), the match is more correct on the Pascel version I'd say.

**Comment by drujensen** [comment]
Thanks @OvermindDL1 I'm not familiar with every compiler and directive.  Is the `inline` directive cheating or will it perform the same recursive call?

**Comment by drujensen** [comment]
Looks like it just inlines the code but doesn't change any functionality, correct?

https://freepascal.org/docs-html/ref/refsu73.html

**Comment by Akira13641** [comment]
> Looks like it just inlines the code but doesn't change any functionality, correct?
> 
> https://freepascal.org/docs-html/ref/refsu73.html

That's right. Specifically I added it because while for example C and C++ compilers inline function calls automatically at their discretion regardless of whether there's any `inline` marker present, Free Pascal does not do that, and simply will not ever inline a function unless it actually has the `inline` modifier.

**Comment by OvermindDL1** [comment]
Yep, what @Akira13641 said.  :-)

**Comment by drujensen** [comment]
@Akira13641 Is there any changes needed to compile this? If so, can you add any switches needed here  https://github.com/drujensen/fib/blob/master/run.sh#L39?  I noticed inline may need this to include `-Si`

**Comment by Akira13641** [comment]
`-Si` is often in the default configuration file for your FPC installation, but I added it to the script anyways just in case as it doesn't matter if it's set twice.

**Comment by drujensen** [comment]
@Akira13641 Thanks.

**Pull request merged**
