### PR TITLE
Add iterative Elixir example

### PR DESCRIPTION
**Pull request by obahareth**
The Elixir code wasn't making use of a core language feature that's built to make recursion more efficient, [Tail call optimization](https://www.culttt.com/2016/06/06/understanding-recursion-tail-call-optimisation-elixir/). This should make it run in less than a second compared to more than 60 seconds before (including compilation time).

All thanks goes to this article:
https://www.stridenyc.com/blog/tail-call-optimization-with-fibonacci-in-elixir

EDIT
I modified it to print the 47th number because the number other examples are calculating is the 47th according to [this version of the sequence](http://www.maths.surrey.ac.uk/hosted-sites/R.Knott/Fibonacci/fibtable.html).

### CODE REVIEW

**Comment by obahareth** [comment]
Here are the results of running `time elixir Fib.exs` on a late 2016 15" Macbook Pro.

```
0.39s user 0.21s system 126% cpu 0.473 total
```

**Comment by pichi** [comment]
This code no longer uses same recursive formula F_n = F_n-1 + F_n-2 as C and other correct submission does
```c
long fib(long n) {
  if (n <= 1) return 1;
  return fib(n - 1) + fib(n - 2);
}
```
This is not competition how you can cheat out fastest solution but how real recursion in each language performs.

**Comment by obahareth** [comment]
I think there’s been a misunderstanding, I’m not cheating anything out, I saw the README mention cases about languages that don’t use tail call optimization, and I know Elixir has it so I thought it’s ok to utilize it?

Also, this is 100% recursion with no tricks.

**Comment by pichi** [comment]
This benchmark is intended to call the function twice. The thing is, that Nim, Crystal, C++, C, Rust and D compilers can do some clever tricks to make one of those two recursive calls actually tail call. But they still have the same recursive formula and do not change the way how its computed and number of operations performed. Your code is faster than those natively compiled languages, nothing clicks?

**Comment by pichi** [comment]
Yeah, it seems.

**Comment by brightball** [comment]
I don't really follow the rationale here either. The original used the scripting form `exs` which is for scripting instead of the `ex` which is precompiled. In Elixir/Erlang, virtually everything operates with recursion and because of that, the language is highly optimized for it. Writing recursive code that isn't structured for tail call optimization is generally considered bad form if it's avoidable. Recursion is used for basic looping in Elixir.

The other examples that you showed for optimized code that broke the benchmark all used some form of caching, while this one uses none. Because of that, I honestly don't understand why @obahareth's PR doesn't qualify.

It seems like the main objection is that it's faster than expected. If TCO or compiler optimizations are a problem in the other languages, then maybe it makes sense to create another section for optimized with no caching benchmarks to show those distinctions?

**Comment by OvermindDL1** [comment]
@brightball The issues is not that it is becoming TCO, it is that it is changing the algorithm from calling 2 tree depths worth of functions each to calling none.  I.E. the algorithm was changed from exponential (the purpose the benchmark) to becoming linear, thus it is no longer matching the testing algorithm.

I've no doubt a TCO version of the original algorithm would be accepted however, but there is no point as the BEAM has unbounded stack growth in both directions and thus the TCO version would probably actually be slower then due to extra copying on the stack.  What does need to be changed is to change the BEAM JIT used for this from the IO optimized JIT to the numerical optimized JIT (HiPE), of which I've already opened an issue about.

**Comment by agrison** [comment]
I agree with @brightball regarding the fact that some languages encourage TCO and not using it is often seen as bad. But it's also true that comparing two recursive calls and one seems off.

Interestingly as [stated on HN](https://news.ycombinator.com/item?id=18095783) the -O3 optimization switch of gcc removes a recursive call: https://godbolt.org/z/oS3Cju 

Should it be also compiled without this switch ?

Maybe some specific directories should be created for different algorithms (TCO, memoization, specific compiler optimization, and purely naive implementations).

**Comment by OvermindDL1** [comment]
> Maybe some specific directories should be created for different algorithms (TCO, memoization, specific compiler optimization, and purely naive implementations).

That's been my thinking.  As for the compiler optimization I think part of the purpose of this repo (correct me if I'm wrong) is precisely what that this is testing, how well a given compiler optimizes a set of bad but easy to read and write code.  It would be interesting to see the differences if split in directories though.  Perhaps directory trees actually... hmm...

**Comment by obahareth** [comment]
I definitely agree with the different directories idea, because this isn’t caching and it’s pure recursion, but it is technically a different algorithm.

**Comment by OvermindDL1** [comment]
@obahareth The algorithm here is iteration, linear.  Recursion is just a pattern, not an algorithm.

**Comment by obahareth** [comment]
I'll restructure this PR however works for this repo, and I'm willing to help with any directory changes if the maintainers need any 😄

**Comment by obahareth** [comment]
Sure @drujensen, but this isn't using memoization, do you mind if I name it `Fib-tco.exs` ? (tail call optimized)

**Comment by obahareth** [comment]
Looks like this PR along with #67 have been mistakenly labeled as memoization but they're just changes to make use of tail call optimizations to reduce the number of stack frames. What about having the following directories/solutions:

* Regular (the standard algorithm with no modifications).
* Tail call optimized (programmer changes to how fib is called to make use of a language's tail call optimization).
* Memoized (Anything that utilizes caching in calculations).
* etc.

**Comment by OvermindDL1** [comment]
> Sure @drujensen, but this isn't using memoization, do you mind if I name it Fib-tco.exs ? (tail call optimized)

Actually it's an iterative algorithm, TCO is inconsequential to how it is working in this case.

**Comment by obahareth** [comment]
Alright, thanks for educating me 🙂, let me know how I should proceed when you’re ready 😄.

**Comment by drujensen** [comment]
@obahareth If you are still interested in providing this, can you move it to the optimized filter and change it to Fib-iterative.exs or something like that?  If not, I will close this out.

**Comment by obahareth** [comment]
Sure @drujensen, I'll get on it. Should contributors update the benchmarks in the README or should that be left to the maintainers?

**Comment by drujensen** [comment]
@obahareth thanks.  You can add it to the `run.sh` which generates the benchmark sections for me.

**Comment by obahareth** [comment]
Done, I wasn't sure how to compile and run a `.ex` and left it as the scripted form `.exs` and so, the benchmark will still include compilation time for this example.

**Comment by obahareth** [comment]
@drujensen Is it fine like this?

**Pull request merged**
