### PR TITLE
add clojure

### PR DESCRIPTION
**Pull request by colonelrascals**
Added fibonacci sequence in clojure

### CODE REVIEW

**Comment by drujensen** [comment]
@colonelrascals Thanks for adding this.  I have no idea what this code is doing.  lol.  I guess its time to find out how clojure works.

Can you add a line in the readme on the best way to compile/run this?

**Comment by OvermindDL1** [comment]
Clojure is just a modern lisp'y language that runs on the JVM.  What this is doing is building up a memoized list of results, then filling it out up to the requested number until it returns the entire list (not just the value), so it goes in the cheating section, in addition to not printing the correct output.

**Comment by OvermindDL1** [comment]
Perhaps it's good to make directories based on the algorithm used.  :-)

**Comment by OvermindDL1** [comment]
Oh, and if you want to run it just something like `clojure fib.clj` is fine, let me do it right quick...
```zsh
╰─➤  time clojure fib.clj
[0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 24157817 39088169 63245986 102334155 165580141 267914296 433494437 701408733 1134903170]
clojure fib.clj  2.06s user 0.12s system 199% cpu 1.096 total
```
Most of that time is spooling up the JVM though.

**Comment by OvermindDL1** [comment]
And honestly, if you want to learn a modern Lisp'y language and don't want to be tied to the JVM, nothing beats [Racket](https://racket-lang.org/) right now.  :-)

**Comment by drujensen** [comment]
@colonelrascals I'm not completely sure but this looks like a memoized version, correct?

Can you provide one that more closely matches the others with 2 recursive calls being added together?  This is the main purpose of this project. 
```ruby
def fib(n)
  return 1 if n <= 1
  fib(n - 1) + fib(n - 2)
end
```

**Comment by drujensen** [comment]
merged a clojure version #82 Closing this PR.  If you want to submit this as an optimized one, add it to the `optimized` directory.  Thanks!

**Pull request closed without merging**
